name: mhpc-project
channels:
  - conda-forge
  - pyviz
  - stefanocampanella
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - dask
  - dask-jobqueue
  - jupyter
  - jupyterlab
  - nodejs
  - geotop
  - pyarrow
  - holoviz
  - pip:
      - git+https://github.com/stefanocampanella/GEOtoPy@master
      - nevergrad
      - git+https://github.com/AIworx-Labs/chocolate@master
      - salib
      - papermill
      - nteract-scrapbook
      - jupyter-book
      - tqdm
      - hiplot
