name: mhpc-project
channels:
  - conda-forge
  - stefanocampanella
dependencies:
  - python < 3.9
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas >= 1.1.0
  - matplotlib
  - seaborn
  - dask
  - dask-jobqueue
  - jupyterlab
  - nodejs
  - geotop
  - pyarrow
  - pip:
      - git+https://github.com/stefanocampanella/GEOtoPy@master
      - nevergrad
      - salib
      - papermill
      - scrapbook
      - jupyter-book
      - tqdm
