name: mhpc-project
channels:
  - default
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - dask
  - dask-jobqueue
  - joblib
  - jupyterlab
  - nodejs
  - geotop
  - pip:
    - nevergrad
    - salib
    - hiplot
    - git+https://github.com/stefanocampanella/GEOtoPy@master
    - git+https://github.com/AIworx-Labs/chocolate@master
    - tqdm
    - papermill
    - scrapbook
    - jupyter-book
variables:
  NUMEXPR_NUM_THREADS: 1
  NUMEXPR_MAX_THREADS: 1
  OMP_NUM_THREADS: 1
  TMPDIR: '/dev/shm'
  PYTHONPATH: '$PYTHONPATH:$MHPCPROJECT_ROOT'


