name: mhpc-project
channels:
  - conda-forge
  - pyviz
  - stefanocampanella
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - dask
  - dask-jobqueue
  - jupyterlab
  - nodejs
  - geotop
  - pyarrow
  - holoviz
  - pip:
      - geotopy
      - nevergrad
      - salib
      - papermill
      - nteract-scrapbook
      - jupyter-book
      - hiplot
      - tqdm
