name: mhpc-project
channels:
  - default
  - conda-forge
  - stefanocampanella
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - dask
  - dask-jobqueue
  - joblib
  - jupyterlab
  - nodejs
  - geotop
  - pip:
    - nevergrad
    - salib
    - hiplot
    - git+https://github.com/stefanocampanella/GEOtoPy@master
    - git+https://github.com/AIworx-Labs/chocolate@master
    - joblib
    - tqdm
    - papermill
    - scrapbook
    - jupyter-book
