temporary-directory: /tmp
distributed:
  temporary-directory: /tmp
  comm:
    retry:
      count: 4
    offload: false
    socket-backlog: 4096
    timeouts:
      connect: 60s
      tcp: 90s
  scheduler:
    unkown-task-duration: 180s
  logging:
    distributed: info
    bokeh: critical
    tornado: critical
  worker:
    use-file-locking: false
