distributed:
  scheduler:
    allowed-failures: 32
  worker:
    use-file-locking: false
    memory:
      target: false
      spill: false
      pause: 0.80
      terminate: 0.95
    allowed-failures: 32
  comm:
    timeouts:
      connect: 20
    compression: null
