distributed:
  worker:
    use-file-locking: false
    memory:
      target: false
      spill: false
      pause: 0.80
      terminate: 0.95
    allowed-failures: 32
  comm:
    compression: null

jobqueue:
  slurm:
    name: dask-worker
    queue: regular2
    walltime: '00:20:00'
    cores: 4
    processes: 1
    memory: 2GB
    interface: ib0
    local-directory: $TMPDIR
    job-extra: 
      - '--hint=nomultithread'
      - '--hint=compute_bound'
      - '--output=/dev/null'
      - '--error=/dev/null'
    extra:
      - '--lifetime 26m'
      - '--lifetime-stagger 2m'

