distributed:

  logging:
    distributed: info
    bokeh: critical
    tornado: critical

  scheduler:
    allowed-failures: 8 # really depends on if using jobqueue or not
    idle-timeout: 1h

  worker:
    use-file-locking: false
    memory:
      target: false
      spill: false
      pause: 0.80
      terminate: 0.95
    allowed-failures: 32
  comm:
    offload: False
    socket-backlog: 4096
    timeouts:
      connect: 20
    compression: null


