jobqueue:
  slurm:
    name: dask-worker

    # Dask worker options
    cores: 4                   # Total number of cores per job
    memory: 2GB                # Total amount of memory per job
    processes: 1               # Number of Python processes per job
    interface: ib0             # Network interface to use like eth0 or ib0
    death-timeout: 60          # Number of seconds to wait if a worker can not find a scheduler
    local-directory: $TMPDIR   # Location of fast local storage like /scratch or $TMPDIR

    # SLURM resource manager options
    shebang: "#!/usr/bin/env bash"
    queue: regular2
    project: null
    walltime: '00:20:00'
    extra:
      - '--lifetime 18m'
      - '--lifetime-stagger 1m'
    env-extra:
      - 'NUMEXPR_NUM_THREADS=1'
      - 'NUMEXPR_MAX_THREADS=1'
      - 'OMP_NUM_THREADS=1'
      - 'TMPDIR=/dev/shm'
    job-cpu: 4
    job-mem: 2GB
    job-extra:
      - '--hint=nomultithread'
      - '--hint=compute_bound'
    log-directory: /dev/shm
