title: "An Empirical Study on the Calibration of the GEOtop Model Using Supercomputers"
author: Stefano Campanella
copyright: "2020"
logo: assets/logo.png

execute:
  execute_notebooks: "off"

html:
  home_page_in_navbar: false
  baseurl: https://stefanocampanella.github.io/MHPC-project
