title: "An empirical study on the calibration of the GEOtop model using supercomputers"
author: Stefano Campanella
copyright: "2020"
logo: assets/logo.png

execute:
  execute_notebooks: "off"

html:
  home_page_in_navbar: false
  baseurl: https://stefanocampanella.github.io/MHPC-project

bibtex_bibfiles:
  - references.bib

latex:
  latex_documents:
    targetname: book.tex
  latex_engine: lualatex

sphinx:
  config:
    latex_elements:
      papersize: a4paper
      geometry: \usepackage[a4paper]{geometry}
      pointsize: 11pt
      extraclassoptions: openany
      fontpkg: |
        \setmainfont{FiraSans}
        \setmonofont{Inconsolata}
      preamble: |
        \usepackage{lualatex-math}
        \usepackage{unicode-math}
        \setmathfont{STIX Two Math}
        \usepackage{microtype}
